# Generated by Django 3.2.7 on 2022-03-22 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curseName', models.CharField(max_length=50, verbose_name='Course Name')),
                ('courseCradit', models.CharField(max_length=1, verbose_name='Cradit')),
                ('courseFees', models.CharField(max_length=5, verbose_name='Fess')),
            ],
            options={
                'verbose_name': 'Courses',
                'verbose_name_plural': 'Coursess',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FastName', models.CharField(max_length=50, verbose_name='Fast Name')),
                ('lestName', models.CharField(max_length=50, verbose_name='Lest Name')),
                ('FatherName', models.CharField(max_length=50, verbose_name='Father Name')),
                ('MotherName', models.CharField(max_length=50, verbose_name='Mother Name')),
                ('Phonenumber', models.CharField(max_length=50, verbose_name='phone number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('img', models.ImageField(upload_to='studentProfile', verbose_name='uploadImage')),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stutentMenage.courses', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fastpay', models.CharField(max_length=5, verbose_name='Fast Payment')),
                ('sectpay', models.CharField(max_length=5, verbose_name='Secount Payment')),
                ('thirdtpay', models.CharField(max_length=5, verbose_name='third Payment')),
                ('studentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stutentMenage.student', verbose_name='studentID')),
            ],
            options={
                'verbose_name': 'Payments',
                'verbose_name_plural': 'Paymentss',
            },
        ),
    ]
