# Generated by Django 3.2.7 on 2022-03-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stutentMenage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='sectpay',
            field=models.CharField(default=None, max_length=5, verbose_name='Secount Payment'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='thirdtpay',
            field=models.CharField(default=None, max_length=5, verbose_name='third Payment'),
        ),
    ]
