# Generated by Django 3.2.7 on 2022-03-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stutentMenage', '0002_auto_20220322_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='sectpay',
            field=models.CharField(default='', max_length=5, verbose_name='Secount Payment'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='thirdtpay',
            field=models.CharField(default='', max_length=5, verbose_name='third Payment'),
        ),
    ]
