# Generated by Django 3.2.7 on 2022-03-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stutentMenage', '0003_auto_20220322_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'verbose_name': 'Payments', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterField(
            model_name='payments',
            name='sectpay',
            field=models.CharField(default=0, max_length=5, verbose_name='Secount Payment'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='thirdtpay',
            field=models.CharField(default=0, max_length=5, verbose_name='third Payment'),
        ),
    ]
