# Generated by Django 3.2.7 on 2022-03-26 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stutentMenage', '0004_auto_20220322_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name': 'courses', 'verbose_name_plural': 'coursess'},
        ),
    ]
