# Generated by Django 3.2.7 on 2022-03-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stutentMenage', '0005_alter_courses_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='fastpaydate',
            field=models.DateTimeField(auto_now=True, verbose_name='fastdate'),
        ),
        migrations.AddField(
            model_name='payments',
            name='secoundpaydate',
            field=models.DateTimeField(auto_now=True, verbose_name='secounddate'),
        ),
        migrations.AddField(
            model_name='payments',
            name='thirdpaydate',
            field=models.DateTimeField(auto_now=True, verbose_name='thirddate'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='fastpay',
            field=models.CharField(default=0, max_length=5, verbose_name='Fast Payment'),
        ),
    ]
