# Generated by Django 3.2.7 on 2022-03-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stutentMenage', '0011_auto_20220328_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='fastpaydate',
            field=models.DateTimeField(auto_now=True, verbose_name='fastdate'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='secoundpaydate',
            field=models.DateTimeField(auto_now=True, verbose_name='secounddate'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='thirdpaydate',
            field=models.DateTimeField(auto_now=True, verbose_name='thirddate'),
        ),
    ]
