# Generated by Django 3.2.7 on 2022-04-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stutentMenage', '0015_cirtificateid'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='descriptions',
            field=models.CharField(default=None, max_length=150, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='courses',
            name='regularFees',
            field=models.CharField(default=100, max_length=50, verbose_name='regular Fess'),
        ),
        migrations.AlterField(
            model_name='cirtificateid',
            name='catificateId',
            field=models.CharField(default='', max_length=10, unique=True, verbose_name='key'),
        ),
    ]
