# Generated by Django 3.2.7 on 2022-04-21 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stutentMenage', '0017_auto_20220421_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='descriptions',
            new_name='descrip',
        ),
    ]
