# Generated by Django 3.2.7 on 2022-04-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stutentMenage', '0018_rename_descriptions_courses_descrip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='descrip',
            field=models.CharField(max_length=150, verbose_name='description'),
        ),
    ]
