# Generated by Django 3.2.7 on 2022-04-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stutentMenage', '0019_alter_courses_descrip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='descrip',
            field=models.CharField(default='100', max_length=150, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='regularFees',
            field=models.CharField(default='100', max_length=5, verbose_name='regular Fess'),
        ),
    ]
