# Generated by Django 3.2.7 on 2022-04-21 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stutentMenage', '0020_auto_20220421_1950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name': 'courses', 'verbose_name_plural': 'courses'},
        ),
    ]
