# Generated by Django 3.2.7 on 2022-04-21 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stutentMenage', '0021_alter_courses_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='descrip',
            new_name='dy',
        ),
    ]
