# Generated by Django 3.2.7 on 2022-04-21 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stutentMenage', '0022_rename_descrip_courses_dy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='dy',
        ),
    ]
