# Generated by Django 3.2.7 on 2022-04-27 18:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stutentMenage', '0025_auto_20220421_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'WorkDetails',
                'verbose_name_plural': 'WorkDetailss',
            },
        ),
    ]
