# Generated by Django 3.2.7 on 2022-04-28 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stutentMenage', '0026_workdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fastname', models.CharField(max_length=50, verbose_name='First name')),
                ('lestname', models.CharField(max_length=50, verbose_name='lest name')),
                ('phone', models.CharField(max_length=16, verbose_name='phone number')),
                ('location', models.CharField(max_length=150, verbose_name='address')),
                ('website', models.CharField(max_length=150, verbose_name='website')),
                ('language', models.CharField(max_length=150, verbose_name='language')),
                ('bio', models.TextField(verbose_name='Bio ')),
                ('img', models.FileField(default=True, max_length=255, null=True, upload_to='studentProfile/users', verbose_name='img')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Myskill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillname', models.CharField(max_length=50, verbose_name='Name')),
                ('progrss', models.CharField(max_length=3, verbose_name='Progress(%)')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Myskill',
                'verbose_name_plural': 'Myskills',
            },
        ),
    ]
