# Generated by Django 3.2.7 on 2022-04-30 08:03

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stutentMenage', '0027_myskill_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('shortdis', models.TextField(verbose_name='Short Discriptions')),
                ('detiles', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('budget', models.CharField(max_length=50, verbose_name='Budget Price')),
                ('expdate', models.DateField(verbose_name='Expire Date ')),
                ('exptime', models.TimeField(verbose_name='Exprire Time')),
                ('uploaddata', models.DateField(auto_now=True, verbose_name='Curent date')),
                ('uploadtime', models.TimeField(auto_now=True, verbose_name='Exprire Time')),
                ('image', models.ImageField(upload_to='studentProfile/project', verbose_name='Fetcher Image')),
            ],
            options={
                'verbose_name': 'AddTask',
                'verbose_name_plural': 'AddTasks',
            },
        ),
        migrations.CreateModel(
            name='TaskCetagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Catragory Name: ')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('shortdis', models.CharField(max_length=50, verbose_name='short discription: ')),
                ('img', models.ImageField(default='', null=True, upload_to='studentProfile/cetagery', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'TaskCetagory',
                'verbose_name_plural': 'TaskCetagorys',
            },
        ),
        migrations.DeleteModel(
            name='WorkDetails',
        ),
        migrations.AddField(
            model_name='addtask',
            name='cetid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stutentMenage.taskcetagory', verbose_name='Task Cetagory'),
        ),
    ]
