# Generated by Django 3.2.7 on 2022-04-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stutentMenage', '0029_alter_taskcetagory_shortdis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcetagory',
            name='img',
            field=models.ImageField(upload_to='studentProfile/cetagery', verbose_name='Image'),
        ),
    ]
