# Generated by Django 3.2.7 on 2022-05-01 07:02

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stutentMenage', '0030_alter_taskcetagory_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtask',
            name='detiles',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addtask',
            name='image',
            field=models.ImageField(upload_to='studentProfile/project', verbose_name=' Image'),
        ),
        migrations.AlterField(
            model_name='addtask',
            name='uploadtime',
            field=models.TimeField(auto_now=True, verbose_name='Curent Time'),
        ),
    ]
