# Generated by Django 3.2.7 on 2022-05-01 08:15

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stutentMenage', '0033_alter_addtask_detiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtask',
            name='detiles',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
