# Generated by Django 3.2.7 on 2022-05-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stutentMenage', '0034_alter_addtask_detiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtask',
            name='image',
            field=models.ImageField(upload_to='studentProfile/project', verbose_name='Image'),
        ),
    ]
