# Generated by Django 3.2.7 on 2022-05-02 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stutentMenage', '0036_alter_addtask_detiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSubCetagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Catragory Name: ')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('shortdis', models.TextField(verbose_name='Short Discriptions')),
                ('img', models.ImageField(upload_to='studentProfile/cetagery', verbose_name='Image')),
                ('cetid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stutentMenage.taskcetagory', verbose_name='Sub Categories')),
            ],
            options={
                'verbose_name': 'TasksubCetagory',
                'verbose_name_plural': 'TasksubCetagorys',
            },
        ),
        migrations.AddField(
            model_name='addtask',
            name='subcatid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stutentMenage.tasksubcetagory', verbose_name='Sub Categories'),
        ),
    ]
