# Generated by Django 3.2.7 on 2022-05-02 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stutentMenage', '0037_auto_20220502_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtask',
            name='subcatid',
        ),
        migrations.DeleteModel(
            name='TaskSubCetagory',
        ),
    ]
