# Generated by Django 3.2.7 on 2022-05-05 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stutentMenage', '0039_remove_addtask_exptime'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tastId', models.CharField(max_length=8, unique=True, verbose_name='Unice Id')),
                ('status', models.CharField(max_length=10, verbose_name='Status')),
                ('bitUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Users ')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stutentMenage.addtask', verbose_name='')),
            ],
            options={
                'verbose_name': 'BitTask',
                'verbose_name_plural': 'BitTasks',
            },
        ),
    ]
