# Generated by Django 3.2.7 on 2022-05-07 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stutentMenage', '0040_bittask'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bituploadproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('file', models.FileField(upload_to='projectfils/', verbose_name='File')),
                ('bitId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stutentMenage.bittask', verbose_name='Bit Id')),
            ],
            options={
                'verbose_name': 'Bituploadproject',
                'verbose_name_plural': 'Bituploadprojects',
            },
        ),
    ]
