# Generated by Django 3.2.7 on 2022-05-10 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stutentMenage', '0043_reviewprojectnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stutentMenage.bittask', verbose_name='Bit Id ')),
            ],
            options={
                'verbose_name': 'BitPayment',
                'verbose_name_plural': 'BitPayments',
            },
        ),
    ]
