# Generated by Django 3.2.7 on 2022-05-10 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stutentMenage', '0044_bitpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitpaymentAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=50, verbose_name='Amount')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Id')),
            ],
            options={
                'verbose_name': 'BitpaymentAmount',
                'verbose_name_plural': 'BitpaymentAmounts',
            },
        ),
        migrations.CreateModel(
            name='PamentOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankname', models.CharField(max_length=50, verbose_name='Bank Name ')),
                ('number', models.CharField(max_length=50, verbose_name='number ')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Id')),
            ],
            options={
                'verbose_name': 'PamentOptions',
                'verbose_name_plural': 'PamentOptionss',
            },
        ),
        migrations.DeleteModel(
            name='BitPayment',
        ),
    ]
